/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/channel/pdfs` | `/channel/pdfs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/landing` | `/landing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/channel/[id]` | `/channel/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/channel/pdfs` | `/channel/pdfs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/landing` | `/landing`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/channel/[id]` | `/channel/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/channel/pdfs${`?${string}` | `#${string}` | ''}` | `/channel/pdfs${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/landing${`?${string}` | `#${string}` | ''}` | `/landing${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/channel/pdfs` | `/channel/pdfs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/landing` | `/landing`; params?: Router.UnknownInputParams; } | `${'/(app)'}/channel/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/channel/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/channel/[id]` | `/channel/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
